### ISSUE TITLE
Interval setting for docker

### ISSUE THREAD

**Issue by RadRotaryShampoo** [mpepping/solarman-mqtt#108]
Hey,

is there a way to pass the interval parameter when running the script in a container? I tried putting it in docker run command, however it's not parsed correctly resulting in container not being started.

Regards

**Comment by RadRotaryShampoo** [comment]
Okay, it's possbile to modify the default interval variable in solarman/__init__.py file, which is then used when the container is created with docker run command.

**Comment by kingp0dd** [comment]
> Okay, it's possbile to modify the default interval variable in solarman/**init**.py file, which is then used when the container is created with docker run command.

i'm using docker-compose, is it also possible there?
