### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by j3sk0** [mpepping/solarman-mqtt#11]
ERROR:root:Error on start: can only concatenate str (not "NoneType") to str
INFO:root:Starting daemonized with a 300 seconds run interval

**Comment by mpepping** [comment]
@j3sk0 the current main branch version (v0.3.0 or `latest` tag for the container-image) contains a `--validate` flag which can be used to validate the config file.

**Comment by j3sk0** [comment]
hi i have pull the last contaner image, now the log sayś:

Traceback (most recent call last):
  File "/opt/app-root/src/run.py", line 11, in <module>
    import mqtt
  File "/opt/app-root/src/mqtt.py", line 7, in <module>
    from paho.mqtt import client as mqtt_client

**Comment by mpepping** [comment]
@j3sk0 Sorry for that! Can you try using the latest container-image version?:
https://github.com/mpepping/solarman-mqtt/pkgs/container/solarman-mqtt

If you still see issues, just let me know.

**Comment by mpepping** [comment]
Fixed via #13

**Comment by jaisonreiter** [comment]
how can help me?

![image](https://github.com/user-attachments/assets/cf6c3d34-fabe-4252-a72c-36308f3b19b8)
