### ISSUE TITLE
screenshot 

### ISSUE THREAD

**Issue by j3sk0** [mpepping/solarman-mqtt#27]
![image](https://user-images.githubusercontent.com/47504442/153775463-0d1042c7-e196-4adb-9c7b-cf1910c4ecf1.png)

how did you create that beautiful picture? can you share the dashboard?

**Comment by mpepping** [comment]
@j3sk0 these are default views in the more recent home assistent releases. Should be visible on `/energy` of your home assistant server, and configurable via `/config/energy/dashboard`.
The individual views can be added to other pages aswel: https://www.home-assistant.io/lovelace/energy/
