### ISSUE TITLE
docker-compose run.py is not found

### ISSUE THREAD

**Issue by HakamSaffour** [mpepping/solarman-mqtt#41]
Hello,
I followed the instruction and installed the docker container using docker-compose

on the docker logs, I am getting the following error, and the container keeps restarting
 
`python: can't open file '/opt/app-root/src/run.py': [Errno 2] No such file or directory`

any advise?

**Comment by cooling75** [comment]
When I remember correctly I had the same issue and mitigated it switching from:
```yaml
volumes:
      - /opt/solarman-mqtt:/opt/app-root/src # source dir must contain you config file
```
to only mounting the config file instead of the whole directory:
```yaml
volumes:
      - ./solarman-mqtt/config.json:/opt/app-root/src/config.json
```

**Comment by HakamSaffour** [comment]
Thanks @cooling75 

Your suggestion solved the issue.
I will make a merge request to correct it on the documentation
