### ISSUE TITLE
AppID is to long

### ISSUE THREAD

**Issue by SeSchi77** [mpepping/solarman-mqtt#60]
I receive today my app id from solarman and it is to long for the config.json if I validate the config.
The app id has 16 numbers.

**Comment by mpepping** [comment]
That should be resolved by now via #61. This is fixed in the latest version and v0.8.2.
The AppId can now either be 15 or 16 chars. 

You can find the [whole schema here](https://github.com/mpepping/solarman-mqtt/blob/main/solarman/helpers.py#L30-L49).
