### ISSUE TITLE
Unable to fetch token: 'access_token'

### ISSUE THREAD

**Issue by giovanne123** [mpepping/solarman-mqtt#68]
Since yesterday I get following error (with latest version):
Nothing changed :-(
Is it still working for you?

```
root@raspberrypi:/home/pi/solarman-mqtt# python3 run.py -s
ERROR:root:Unable to fetch token: 'access_token'
```

**Comment by finfin82** [comment]
same here... i have no idea, how to fix it?!

**Comment by giovanne123** [comment]
for me too still not working. 
Maybe solarman has changed something ... ?

**Comment by mpepping** [comment]
Looking back in my own logging I see the same message, earlier this year. It does seem to something on the remote end.

For myself, it’s still working OK. That make reproducing the issue a bit hard. Is it possible to add `"debug": true` as a top-level option in the config file and try again? Hopefully that gives an insight in what’s going on.

**Comment by finfin82** [comment]
setting is set to debug: true but i cant get any additional information

**Comment by farnos85** [comment]
Same issue here since yesterday 10.17 PM.

with debug: true I have only this error:
ERROR:root:Unable to fetch token: 'access_token'

**Comment by giovanne123** [comment]
Right, with debug on there no more output:
```
pi@rpi:/home/pi/solarman-mqtt# python3 run.py -s
ERROR:root:Unable to fetch token: 'access_token'
root@raspberrypi:/home/pi/solarman-mqtt#


```
So, I think it is something on the solarman end, maybe they have changed something to restrict us to use the API ;-)
(good to have the reading in parallel locally via MODBUS running :-))

Today I tried from the beginning for solarman-mqtt, started by creation of a simplier password, created the new passhash and tried to get the needed infos for the config:
```
curl --location --request POST 'https://api.solarmanpv.com/account/v1.0/token?appId=MYAPPID&language=en'   --header 'Content-Type: application/json'   --data-raw '{
  "appSecret": "MYAPPSECRET",
  "email": "MYEMAIL",
  "password": "MYPASSWORDHASHED"
}'
{"code":"2101010","msg":"appId insufficient allowance","success":false,"requestId":"f9729c57aaMYMODIFIED"}
```
--> **appId insufficient allowance**

I wrote an email to solarman support to let them check my APPID


@farnos85, @finfin82 , maybe you can try if this is still working for you?
@mpepping , can you still call this "curl..."?

**Comment by farnos85** [comment]
@giovanne123 same response:
`{"code":"2101010","msg":"appId insufficient allowance","success":false,"requestId":"6bfbbb53dead50fb"}`

Please let us know if you receive any answer by solarman support.

**Comment by finfin82** [comment]
hello are there any news? seems like during the night - there was a small time data available, watching my loggings i can see 1-2 value sets

**Comment by giovanne123** [comment]
No, for me no change and so far no response from solarman support....

**Comment by mpepping** [comment]
For me it's still working OK: `{"code":null,"msg":null,"success":true,"requestId":"0ac081893e78c5 [..]}`

'insufficient allowance' sounds appid related indeed. Emailing <mailto:service@solarmanpv.com> is the only option here I think. I'm curious to their response though.

**Comment by giovanne123** [comment]
For me is working again, after I got answer from solarman support:
"The number of interface calls has been adjusted..."

**Comment by mpepping** [comment]
Good to hear, @giovanne123. I’ll add it to the README
