### ISSUE TITLE
New API endpoint

### ISSUE THREAD

**Issue by jdeluyck** [mpepping/solarman-mqtt#69]
I got this in the mail today:

> We are delighted to inform you that SOLARMAN platform will upgrade data centers from 2023-04-16 09:00 to 2023-04-16 18:00 (UTC+8) , as part of our continued efforts to offer you a premium product.
> 
> Please note that  your account and data will not be accessible via the interface until the upgrade is completed.
> 
> Once upgrade is completed, if you are using the "International Data Center", we kindly remind that you use the new OPENAPI domain globalapi.solarmanpv.com to access the platform, replacing the previous domain api.solarmanpv.com. Your APPID and APPSECRET will remain the same, but you will need to obtain a new token to access the platform.
>

**Comment by mpepping** [comment]
Ah, good catch. Updating the config.json file should be sufficient:
https://github.com/mpepping/solarman-mqtt/blob/main/config.sample.json#L3 

I’ll update the example as well.

**Comment by pmitrus** [comment]
Today around 22 stopped to work on api.solarmanpv.com, so I switched to globalapi and now only shows "Unable to fetch token".  And goes to 300s pause. How other users?

**Comment by mpepping** [comment]
Same here, different message though. The old API is offline and the new one throws a "Service currently unavailable"

```
INFO:root:{
    "code": "3201001",
    "msg": "Service Currently Unavailable",
    "requestId": "8ce013f8b5b564fc",
    "success": false
}

INFO:root:{
    "code": "3201001",
    "msg": "Service Currently Unavailable",
    "requestId": "be96b94b88117923",
    "success": false
}
```

Let's hope it gets resolved anytime soon.

**Comment by pmitrus** [comment]
started :)

```
INFO:root:"INVERTER DATA"
INFO:root:{
    "code": null,
    "collectionTime": 1681802560,
    "deviceId": 217845260,
    "deviceSn": "T620400072235729",
    "deviceState": 1,
    "deviceType": "INVERTER",
    "msg": null,
    "requestId": "137f97daa45c7936",
    "success": true
}
```

**Comment by mpepping** [comment]
> started :)
> 

Ah, fortunately that didn't took too long.

**Comment by mt-mrx** [comment]
Thanks for opening this issue from me as well, the initial notification mail was handled/sorted by my SPAM filter. ;-)
