### ISSUE TITLE
ERROR:root:Error on start: 'dataList'

### ISSUE THREAD

**Issue by hrsmilda** [mpepping/solarman-mqtt#7]
hello,
I run de latest version of solarman-mqtt in docker. Once a day de docker stop running and in de logging I see the next error:

ERROR:root:Error on start: 'dataList'

There is no extra information in de logging. Is this a known error or is this new to you?

Is there a solution for this problem?

Richard

**Comment by lechk82** [comment]
> hello, I run de latest version of solarman-mqtt in docker. Once a day de docker stop running and in de logging I see the next error:
> 
> ERROR:root:Error on start: 'dataList'
> 
> There is no extra information in de logging. Is this a known error or is this new to you?
> 
> Is there a solution for this problem?
> 
> Richard

It's possible that datalist might not be available sometimes. Currently, there are no mechanisms implemented that handle this. For now, I would suggest setting the docker container start policy to "unless-stopped" until the problem is fixed.

**Comment by mpepping** [comment]
@hrsmilda fixed in the latest version:
https://github.com/mpepping/solarman-mqtt/pkgs/container/solarman-mqtt

**Comment by giondo** [comment]
Hi same issue  here
INFO:root:Starting daemonized with a 300 seconds run interval
ERROR:root:Error on start: 'dataList'

anything  I can do about it?

Thanks!

**Comment by giondo** [comment]
forget about it, just found  the solution on  another issue... need to use Serial numbers instead of device IDs
Documentation should be updated
