### ISSUE TITLE
MQTT Out of memory usage Issue 

### ISSUE THREAD

**Issue by Jabroni** [mpepping/solarman-mqtt#74]
I just upgraded to the new version after having my solarman inverters offline, however Im having some issues pushing the values to the MQTT broker.

Checking the logs on HA mqtt mosquito logs, i see this errors
2023-05-18 10:07:50: New client connected from 192.168.x.x:49135 as solarmanpv-mqtt-655 (p2, c1, k60, u'username').
2023-05-18 10:07:50: Client solarmanpv-mqtt-655 disconnected due to out of memory.

HA is updated to latest version, so is mosquito mqtt server (ver 6.2.1), running on a Pi4 4GB. Checking the memory usage of the Pi it shows just 1-1.3GB RAM usage. 

I have several other mqtt client that connects correctly to the server so its just solarman-mqtt that is having the issue

Enabled the debug logs on the solarman-mqtt docker, and this is what i see 

INFO:root:2023-05-18 18:18:51 - Inverter DeviceState: 1 -> Publishing to MQTT ...

Any idea what could be wrong?

**Comment by mpepping** [comment]
The Out of Memory message itself can also be a confusing error sent by Mosquitto:

https://github.com/eclipse/mosquitto/issues/2525

It's worth testing different QoS classes in te config.json file (0,1 or 2), and secondly check the credentials. MQTT Explorer is a nice tool to check connectivity and browse queue's:

http://mqtt-explorer.com/

**Comment by mpepping** [comment]
Feel free to reopen if this still is an issue @Jabroni!
