### ISSUE TITLE
Compile to ARM

### ISSUE THREAD

**Issue by maumauns** [mpepping/solarman-mqtt#8]
Trying install in my raspberry and im getting errors, mayba cause the compilation is for X86_64 not ARM.

**Comment by lechk82** [comment]
I have extended the docker image for arm: https://github.com/lechk82/solarman-mqtt
I will create a PR in the next days.

**Comment by mpepping** [comment]
ARM64 support is also available as per container tag `0.4` (`0.4.2`), or `latest`.

https://github.com/mpepping/solarman-mqtt/pkgs/container/solarman-mqtt
