### ISSUE TITLE
More than one inverter possible?

### ISSUE THREAD

**Issue by jaal2001** [mpepping/solarman-mqtt#85]
I tried to add an additional inverter, but that produced only an error message. In the end I created an additional docker container to gather the information from the second inverter. So did anyone manage to add an additional one?

**Comment by mpepping** [comment]
Shouldn't be too hard to add support for multiple inverters. For now running two instances is the best option. Will keep this open a reminder to add this as an improvement.

**Comment by mpepping** [comment]
@jaal2001 the version in the main branch (and the `ghcr.io/mpepping/solarman-mqtt:main` image) have support for multiple inverters. See [this section in the README](https://github.com/mpepping/solarman-mqtt/blob/main/README.md#running-multiple-inverter-stations) for usage.


/cc @nicks-technik: maybe relevant for you as well (#31)

**Comment by jaal2001** [comment]
Works perfectly. Suggestion: Improve config.json.example file in this way:

[
{
  "name": "",
  "url": "",
  "appid": "",
  "secret": "",
  "username": "",
  "passhash": "",
  "stationId":,
  "inverterId": "",
  "loggerId": "",
  "debug": false,
  "mqtt":{
    "broker": "",
    "port":,
    "topic": "",
    "username": "",
    "password": "",
    "qos": 1,
    "retain": true
  }

},
{
  "name": "",
  "url": "",
  "appid": "",
  "secret": "",
  "username": "",
  "passhash": "",
  "stationId":,
  "inverterId": "",
  "loggerId": "",
  "debug": false,
  "mqtt":{
    "broker": "",
    "port":,
    "topic": "",
    "username": "",
    "password": "",
    "qos": 1,
    "retain": true
  }
}
]

This could help to identify how to use multiple inverter.

**Comment by mpepping** [comment]
Thanks for confirming, @jaal2001! 

I'll update the `config.sample.json` file according to your suggestion.
